project_id = "edgxhgevaduxnxtfyyfq"

[functions.bootstrap-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.reset-cnpj-data]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.subscription-status]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
